# Generated by Django 6.0.3 on 2026-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
    ]
